name: quizapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  amazon_cognito_identity_dart_2: ^3.5.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.8.3
  provider: ^6.1.1
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  # shared_preferences: ^2.3.3
  #sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
