// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-Elu3yKqgsTOj5gXzYEW6rkyVgiqQ2U',
    appId: '1:375064665660:web:258197dd07b3f678052d39',
    messagingSenderId: '375064665660',
    projectId: 'quizapp-4d983',
    authDomain: 'quizapp-4d983.firebaseapp.com',
    storageBucket: 'quizapp-4d983.firebasestorage.app',
    measurementId: 'G-BS54LMG4XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qJTtmeeDDpIhvvw3cg7oJ0RmdVu3nOE',
    appId: '1:375064665660:android:bf67a62332809877052d39',
    messagingSenderId: '375064665660',
    projectId: 'quizapp-4d983',
    storageBucket: 'quizapp-4d983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Skz7SNwX8hMS6lRkTFZ0K5yQs1zcd5Q',
    appId: '1:375064665660:ios:188c948fe481c198052d39',
    messagingSenderId: '375064665660',
    projectId: 'quizapp-4d983',
    storageBucket: 'quizapp-4d983.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Skz7SNwX8hMS6lRkTFZ0K5yQs1zcd5Q',
    appId: '1:375064665660:ios:188c948fe481c198052d39',
    messagingSenderId: '375064665660',
    projectId: 'quizapp-4d983',
    storageBucket: 'quizapp-4d983.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK-Elu3yKqgsTOj5gXzYEW6rkyVgiqQ2U',
    appId: '1:375064665660:web:348a4821c31e318f052d39',
    messagingSenderId: '375064665660',
    projectId: 'quizapp-4d983',
    authDomain: 'quizapp-4d983.firebaseapp.com',
    storageBucket: 'quizapp-4d983.firebasestorage.app',
    measurementId: 'G-S5C22B9HKH',
  );

}